[package]
name = "ml_kem"
version = "0.1.0"
edition = "2024"

[features]
default = ["std", "getrandom"]
std = ["mlrust_core/std"]
getrandom = ["mlrust_core/getrandom"]


[dependencies]
mlrust_core = {path = "../mlrust_core"}
sha3 = "0.12.0"
shake = { version = "0.1.0", default-features = false }
digest = "0.11.3"

[dev-dependencies]
hex = "0.4"