[package]
name = "ml_dsa"
version = "0.1.0"
edition = "2024"
description = "Pure Rust ML-DSA implementation for the mlrust workspace"
license = "Apache-2.0"
repository = "https://github.com/martin-azon/mlrust"
readme = "README.md"

[features]
default = ["std", "getrandom"]
std = ["mlrust_core/std"]
getrandom = ["mlrust_core/getrandom"]


[dependencies]
mlrust_core = {version = "0.1.0", path = "../mlrust_core", default-features = false}
subtle = "2.6.1"
zeroize = { version = "1", default-features = false }

[dev-dependencies]
sha3 = "0.10" 