[package]
name = "mlrust_core"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
std = []
getrandom = ["dep:getrandom"]

[dependencies]
subtle = { version = "2", default-features = false }
sha3 = { version = "0.12", default-features = false }
shake = { version = "0.1.0", default-features = false }
digest = { version = "0.11", default-features = false }
getrandom = { version = "0.4", optional = true }